services:
  # app:
  #   build:
  #     context: .
  #   env_file:
  #     - .env.cf-dev
  #   user: "${USER_ID}:${GROUP_ID}"
  #   expose:
  #     - "3000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development
  #   command: sh -c "bun run dev:container --mode $${VITE_MODE}"
  #   networks:
  #     - app-network

  proxy:
    image: nginx:alpine
    env_file:
      - .env.cf-dev
    # ports:
      # - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - app
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env.cf-dev
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - proxy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 